{{- if .Values.autoscaling.enabled | default true -}}
apiVersion:  autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "microservice.name" . }}-hpa
  labels:
    {{- include "microservice.labels" . | indent 4}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template  "microservice.name" . }}-deployment
  minReplicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default 3 }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.MemoryUtilizationPercentage | default 80 }}
  - type: Resource           
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.averageCpuUtilizationPercentage | default 80 }}   
{{- end }}
