{{ if and .Values.secretProvider.enabled (eq .Values.secretProvider.provider "azure")}}
{{- range .Values.secretProvider.parameters }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "microservice.name" $ }}-{{ lower .fileName | replace "." "-" | replace "_" "-" }}
  labels:
    {{- include "microservice.labels" $ | indent 4 }}
spec:
  provider: azure
  parameters:
    keyvaultName: {{ .keyvaultName | quote }}       # The name of the Azure Key Vault
    useVMManagedIdentity: {{ .useVMManagedIdentity | quote}}
    userAssignedIdentityID: {{ .userAssignedIdentityID | quote }}
    cloudName: {{ .cloudName | default "AzurePublicCloud" | quote }}          # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    tenantId: {{ .tenantId | quote }}
    objects:  |
      array:
        - |
          objectName: {{ .secretName }}                           
          objectType: secret  
          objectAlias: {{ .fileName | quote }}         
          {{- if .objectVersion}}
          objectVersion: {{ .objectVersion | quote }}
          {{- end }}        
{{- end}}
{{- end}}