{{ if and .Values.secretProvider.enabled (eq .Values.secretProvider.provider "aws")}}
{{- range .Values.secretProvider.parameters }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "microservice.name" $ }}-{{ lower .fileName | replace "." "-" | replace "_" "-" }}
  labels:
    {{- include "microservice.labels" $ | indent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ .secretName | quote }}
          objectType: "secretsmanager"
          objectAlias: {{ .fileName | quote }}
        {{- if .objectVersion}}
          objectVersion: {{ .objectVersion | quote }}
        {{- end }}
        {{- if .objectVersionLabel}}
          objectVersionLabel: {{ .objectVersionLabel | quote }}
        {{- end }}          
{{end}}
{{end}}