{{ if and .Values.secretProvider.enabled (eq .Values.secretProvider.provider "vault")}}
{{- range .Values.secretProvider.parameters }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "microservice.name" $ }}-{{ lower .fileName | replace "." "-" | replace "_" "-" }}
  labels:
    {{- include "microservice.labels" $ | indent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .vaultAddress | quote }}
    roleName: {{ .roleName  | quote }}
    objects: |
      - objectName:  {{ .fileName | quote }}
        secretPath:  {{ .secretPath | quote }}
        secretKey:  {{ .secretKey | quote }}
{{end}}
{{end}}