{{- if .Values.secret.enabled | default false -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microservice.name" . }}-secret
  labels:
    {{- include "microservice.labels" . | indent 4}}
type: Opaque
data:
  {{- include "microservice.secret" . | indent 2 }}
{{- end }}
