{{- if .Values.managedServiceAccount.enabled | default false -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "microservice.serviceAccount" . }}
  {{- if  .Values.serviceAccountAnnotations }}
  annotations:
 {{ toYaml .Values.managedServiceAccount.serviceAccountAnnotations | indent 4 }}
  {{- end }}
  labels:
  {{- include "microservice.labels" . | indent 4 }}
{{- end }}
